wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    framework: huggingface
    huggingface_version: 4.19.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1679041364
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 30
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 30
      - 41
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      4: 3.9.12
      5: 0.12.20
      6: 4.19.2
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 32
data_size:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 3.0e-06
model_name:
  desc: null
  value: cardiffnlp/twitter-xlm-roberta-base-sentiment
